config/routes.rb
RailsExample::Application.routes.draw do
  resources :books

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = Book.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/view_controller.rb
# coding: utf-8

class ViewController < ApplicationController
  def form_tag
    @book = Book.new
  end

  def form_for
    @book = Book.new
    #@book = Book.find(1)
  end

  def field
    @book = Book.new
  end

  def select
    @book = Book.new(:publish => '技術評論社')
  end

  def col_select
    @book = Book.new(:publish => '技術評論社')
    @books = Book.select('DISTINCT publish')
  end

  def col_select2
    @book = Book.new(:publish => '技術評論社')
    @books = Book.select('DISTINCT publish')
  end

  def group_select
    @review = Review.new()
    @authors = Author.all
  end

  def group_select2
    @review = Review.new()
    @authors = Author.all
  end

  def dat_select
    @book = Book.find(1)
  end

  def fields
    @user = User.find(1)
  end

  def conc
    @books = Book.all
  end

  # def default_url_options(options = {})
  #   { :charset => 'utf-8' }
  # end 

  def adopt
    render :layout => 'sub'
  end

  def multi
    render :layout => 'layout'
  end

  def nest
    @msg = '今日も良い天気です。'
    render :layout => 'child'
  end

  def partial_basic
    @book = Book.find(2)
  end

  def partial_param
    @book = Book.find(2)
  end

  def partial_col
    @books = Book.all
  end

  def partial_spacer
    @books = Book.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :publish %><br />
    <%= f.text_field :publish %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.date_select :published %>
    
  </div>
  <div class="field">
  <%= radio_button 'gift', 'price' ,"val1" %>
  <%= radio_button 'gift', 'price' ,"val1" %>
  <%= radio_button 'gift', 'price' ,"val1" %>
  <%= radio_button 'gift', 'price' ,"val1" %>
  </div>
  <div class="field">
  <%= text_area 'gift', 'name' %>
  </div>
    
  
  <div class="actions">
    <%= f.submit %>
  </div>
    
  
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Listing books</h1>

<table>
  <tr>
    <th>Isbn</th>
    <th>Title</th>
    <th>Price</th>
    <th>Publish</th>
    <th>Published</th>
    <th>Cd</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.isbn %></td>
    <td><%= book.title %></td>
    <td><%= book.price %></td>
    <td><%= book.publish %></td>
    <td><%= book.published %></td>
    <td><%= book.cd %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Isbn:</b>
  <%= @book.isbn %>
</p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Price:</b>
  <%= @book.price %>
</p>

<p>
  <b>Publish:</b>
  <%= @book.publish %>
</p>

<p>
  <b>Published:</b>
  <%= @book.published %>
</p>

<p>
  <b>Cd:</b>
  <%= @book.cd %>
</p>



<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/view/field.html.erb
<%= form_for(@book) do |f| %>
  テキストボックス：
  <%= f.text_field :isbn,
    { :size => 20, :maxlength => 25, :read_only => true } %><br />
  パスワードボックス：
  <%= f.password_field :isbn,
    { :size => 10, :maxlength => 15, :disabled => true } %><br />
  テキストエリア：<br />
  <%= f.text_area :isbn,
    { :cols => 40, :rows => 10 } %><br />
  ラジオボタン：
  <label><%= f.radio_button :publish, '技術評論社', { :class => 'rd' } %>
    技術評論社</label>
  <label><%= f.radio_button :publish, '翔泳社', { :class => 'rd' } %>
    翔泳社</label>
  <label><%= f.radio_button :publish, 'マイコミ', { :class => 'rd' } %>
    マイコミ</label><br />
  チェックボックス：
  <label><%= f.check_box :cd, { :class => 'chk'}, 'yes', 'no' %>
    CD付属？</label><br />
  ファイル入力ボックス：
  <%= f.file_field :isbn,
    { :size => 10, :maxlength => 15 } %><br />
  メール入力ボックス：
  <%= f.email_field :isbn,
    { :size => 10, :maxlength => 15 } %><br />
  数値入力ボックス：
  <%= f.number_field :isbn,
    { :size => 10, :maxlength => 15, :step => 10 } %><br />
  範囲フィールド：
  <%= f.range_field :isbn,
    { :size => 10, :maxlength => 15, :max =>100, :min => 0 } %><br />
  検索ボックス：
  <%= f.search_field :isbn,
    { :size => 10, :maxlength => 15 } %><br />
  電話番号入力ボックス：
  <%= f.telephone_field :isbn,
    { :size => 10, :maxlength => 15 } %><br />
  URL入力ボックス：
  <%= f.url_field :isbn,
    { :size => 10, :maxlength => 15 } %><br />
  隠しフィールド：
  <%= f.hidden_field :isbn,
    { :size => 10, :maxlength => 15 } %><br />
<% end %>

app/views/view/form_for.html.erb
<%= form_for(@book) do |f| %>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn, { :size => 25 } %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, { :size => 25 } %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price, { :size => 25 } %>
  </div>
  <div class="field">
    <%= f.label :publish %><br />
    <%= f.text_field :publish, { :size => 25 } %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.text_field :published, { :size => 25 } %>
  </div>
  <div class="field">
    <%= f.label :cd %><br />
    <%= f.text_field :cd, { :size => 25 } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/view/form_tag.html.erb
<%= form_tag({ :action => 'create' }) do %>
  <div class="field">
    <%= label :book, :isbn %><br />
    <%= text_field :book, :isbn, { :size => 25 } %>
  </div>
  <div class="field">
    <%= label :book, :title %><br />
    <%= text_field :book, :title, { :size => 25 } %>
  </div>
  <div class="field">
    <%= label :book, :price %><br />
    <%= text_field :book, :price, { :size => 25 } %>
  </div>
  <div class="field">
    <%= label :book, :publish %><br />
    <%= text_field :book, :publish, { :size => 25 } %>
  </div>
  <div class="field">
    <%= label :book,  :published %><br />
    <%= text_field :book, :published, { :size => 25 } %>
  </div>
  <div class="field">
    <%= label :book, :cd %><br />
    <%= text_field :book, :cd, { :size => 25 } %>
  </div>
  <div class="actions">
    <%= submit_tag '登録' %>
  </div>
<% end %>

app/views/view/keyword.html.erb
<%= form_tag({ :controller => 'keyword', :action => 'search' },
  { :id => 'fm', :class => 'search' }) do %>
  検索キーワード：
  <%= text_field_tag 'keywd', '', { :size => 30 } %>
  <%= submit_tag '検索' %>
<% end %>